course_day4/pokesearch/__init__.py
import dotenv
from pokesearch.logic import read_csv
from flask import Flask


def create_app():
    inner_app = Flask(__name__)
    dotenv.load_dotenv(".flaskenv")
    inner_app.config.from_prefixed_env()
    inner_app.data = read_csv("pokesearch/data/pokemon.csv")
    poke_types = set()
    for record in inner_app.data:
        poke_types.add(record["Type 1"])
        if record["Type 2"]:
            poke_types.add(record["Type 2"])
    inner_app.poke_types = sorted(poke_types)
    poke_gens = set()
    for record in inner_app.data:
        poke_gens.add(record["Generation"])
    inner_app.poke_gens = sorted(poke_gens)

    from pokesearch.routes import main
    from pokesearch.auth import auth

    inner_app.register_blueprint(main)
    inner_app.register_blueprint(auth)

    return inner_app

course_day4/pokesearch/auth.py
from flask import Blueprint, current_app, flash, redirect, request, session, url_for


auth = Blueprint("auth", __name__, url_prefix="/auth")


@auth.post("/login")
def login():
    user_password = request.form["password"]
    if user_password != current_app["PASSWORD"]:
        flash("Incorrect password")
        return redirect(url_for("main.index"))

    session["name"] = request.form["username"]
    return redirect(url_for("main.index"), code=303)


@auth.post("/logout")
def logout():
    session.clear()
    return redirect(url_for("main.index"), code=303)

course_day4/pokesearch/routes.py
#!/usr/bin/env python3

from pokesearch.logic import query
from flask import Blueprint, abort, current_app, render_template, request, session


main = Blueprint("main", __name__, url_prefix="/")


@main.get("/")
def index():
    if not session.get("name", None):
        return render_template("poke_form.html", types=current_app.poke_types)
    return render_template("poke_form.html", types=current_app.poke_types, name=session["name"])


@main.post("/search")
def post_index():
    return render_template("index.html", data=query(dict(request.form)))


@main.route("/<int:pokemon_id>")
def pok_by_id(pokemon_id: int):
    data = [record for record in current_app.data if int(record["ID"]) == pokemon_id]
    if data:
        return render_template("details.html", data=data)
    abort(404)


@main.route("/<string:pokemon_name>")
def pok_by_name(pokemon_name: str):
    data = [record for record in current_app.data if record["Name"] == pokemon_name]
    if data:
        return render_template("details.html", data=data[0])
    abort(404)


@main.errorhandler(404)
def not_found(error):
    return "No pokemon here"

course_day4/pokesearch/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>hello, Pokemon hunters</title>
        <link rel="stylesheet" href="https://unpkg.com/mvp.css">
        <link rel="stylesheet" href={{ url_for('static', filename='styles/style.css') }}>
    </head>
    <body>
        <header>
            <nav>
                <a href='{{ url_for("main.index") }}'>Home</a>
                {% if name %}
                Hello, {{name}}
                <form action="{{url_for('auth.logout')}}" method="post">
                    <input type="submit" name="submit" value="Log out">
                </form>
                {% else %}
                <form action="{{url_for('auth.login')}}" method="post">
                    <label for="username">User name</label>
                    <input type="text" name="username">
                    <label for="password">Password</label>
                    <input type="password" name="password">
                    <label for="remember">Remember me</label>
                    <input type="checkbox" name="remember">
                    <br>
                    <input type="submit" name="submit" value="Log in">
                </form>
                {% endif %}
            </nav>
            <h1>
                Welcome to the <span id="app_title">Pokemon encyclopedia!</span>
            </h1>
        </header>
        <main>
            <section>
                {% block content %}
                {% endblock content %}
            </section>
        </main>
    </body>
</html>

course_day4/pokesearch/templates/details.html
{% extends 'base.html' %}
{% block content %}
{% for monster in data %}
    <header>
        <h2>{{ monster["Name"] }}</h2>
    </header>
    {% for key, value in monster.items() %}
    <aside>
        <h3>{{ key }}</h3>
        <p>{{ value}} </p>
    </aside>
    {% endfor %}
{% endfor %}
{% endblock content %}

course_day4/pokesearch/templates/index.html
{% extends "base.html" %}
{% block content %}
<div>
    {% if data %}
    <h3>Found {{ data | length }} pokemons matching the search criteria.</h3>
        <table>
            <thead>
                {% for col in data[0].keys() %}<th>{{ col }}</th>{% endfor %}
            </thead>
            <tbody>
                {% for row in data %}
                    <tr>
                        {% for key, value in row.items() %}
                            {% if key == "Name" %}
                                <td>
                                    <a href={{ url_for("main.pok_by_id", pokemon_id=row["ID"]) }}>{{ value }}</a>
                                </td>
                            {% elif key == "Legendary" and value %}
                                <td class="legend">✓</td>
                            {% elif key == "Legendary" and not value %}
                                <td>✗</td>
                            {% else %}
                                <td>{{ value }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>
            Nothing found. <a href='{{ url_for("main.index") }}'>Try again</a>
        </p>
    {% endif %}
</div>
{% endblock content %}

course_day4/pokesearch/templates/poke_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post" action="{{ url_for("main.post_index") }}">
    <label for="primary_type">Type</label>
    <select name="primary_type">
        <option value="Any">Any</option>
        {% for type in types %}
        <option value={{type}}>{{type}}</option>
        {% endfor %}
    </select>
    <label for="min_health">Min Health</label>
    <input type="number" name="min_health" min="0">
    <label for="max_health">Max Health</label>
    <input type="number" name="max_health" min="0">
    <input type="submit" value="Search" id="submitBtn">
</form>
{% endblock content %}