research_day9/navigator/models.py
#!/usr/bin/env python3
"""
College navigator data models

@author: Roman Yasinovskyy
@version: 2025.7
"""

from flask_login import UserMixin
from sqlalchemy.orm import Mapped, mapped_column

from navigator import db


class User(UserMixin, db.Model):
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]
    email: Mapped[str] = mapped_column(unique=True)
    password: Mapped[str]


class College(db.Model):
    name: Mapped[str] = mapped_column(primary_key=True)
    city: Mapped[str]
    state: Mapped[str]

research_day9/navigator/forms.py
#!/usr/bin/env python3
"""
College navigator forms

@author: Roman Yasinovskyy
@version: 2025.7
"""

from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, StringField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    email = EmailField("email", validators=[DataRequired()])
    password = PasswordField("password", validators=[DataRequired()])


class SignupForm(FlaskForm):
    email = EmailField("email", validators=[DataRequired()])
    name = StringField("name", validators=[DataRequired()])
    password = PasswordField("password", validators=[DataRequired()])

research_day9/navigator/__init__.py
#!/usr/bin/env python3
"""
College navigator app initialization

@authors: Roman Yasinovskyy
@version: 2025.7
"""

import csv
import pathlib
import sqlite3

import dotenv
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import DeclarativeBase

login_manager = LoginManager()
login_manager.login_view = "auth.login"


class Base(DeclarativeBase):
    pass


db = SQLAlchemy(model_class=Base)


def create_app():
    from navigator.auth import auth
    from navigator.routes import main

    app = Flask(__name__)
    dotenv.load_dotenv(".flaskenv")
    app.config.from_prefixed_env()
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{app.config.get('DB_NAME')}.sqlite3"
    login_manager.init_app(app)
    db.init_app(app)
    if not pathlib.Path(app.config.get("SQLALCHEMY_DATABASE_URI")).exists():
        with app.app_context():
            db.create_all()
        with sqlite3.connect(f"instance/{app.config.get('DB_NAME')}.sqlite3") as connection:
            cursor = connection.cursor()
            with open(f"{app.config.get('DB_NAME')}.csv") as data_file:
                data = csv.DictReader(data_file)
                try:
                    cursor.executemany(
                        "INSERT INTO college VALUES(?, ?, ?);",
                        [tuple(row.values()) for row in data],
                    )
                except sqlite3.IntegrityError:
                    pass

    with sqlite3.connect(f"instance/{app.config.get('DB_NAME')}.sqlite3") as connection:
        connection.row_factory = sqlite3.Row
        cursor = connection.cursor()
        cursor.execute("SELECT * FROM college ORDER BY name;")
    app.data = cursor.fetchall()
    app.register_blueprint(main)
    app.register_blueprint(auth)
    return app

research_day9/navigator/auth.py
#!/usr/bin/env python3
"""
College navigator authentication routes

@author: Roman Yasinovskyy
@version: 2025.7
"""

from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import login_required, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from navigator import db, login_manager
from navigator.forms import LoginForm, SignupForm
from navigator.models import User

auth = Blueprint("auth", __name__, url_prefix="/")

user = User()


@auth.route("/signup", methods=["GET", "POST"])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        email = request.form.get("email")
        name = request.form.get("name")
        password = request.form.get("password")
        user = User.query.filter_by(email=email).first()
        if user:
            flash("User already exists")
            return redirect(url_for("auth.signup"))
        new_user = User(
            email=email,
            name=name,
            password=generate_password_hash(password),
        )
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for("auth.login"))
    return render_template("signup.html", form=form)


@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = request.form.get("email")
        password = request.form.get("password")
        user = User.query.filter_by(email=email).first()
        if not user or not check_password_hash(user.password, password):
            flash("Please check your login details and try again.")
            return redirect(url_for("auth.login"))

        login_user(user)
        flash(f"Welcome, {user.name}")
        return redirect(url_for("main.index"))
    return render_template("login.html", form=form)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).first()

research_day9/navigator/routes.py
#!/usr/bin/env python3
"""
College navigator routes

@author: Roman Yasinovskyy
@version: 2025.7
"""

from flask import Blueprint, current_app, render_template
from flask_login import login_required

main = Blueprint("main", __name__, url_prefix="/")


@main.route("/")
def index():
    return render_template("index.html", data=current_app.data)


@main.get("/profile")
@login_required
def profile():
    return render_template("index.html")

research_day9/navigator/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="Guessing game">
        <meta name="keywords" content="flask, jinja, html, bootstrap">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://unpkg.com/mvp.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <title>College Navigator</title>
    </head>
    <body>
        <header>
            <nav>
                <a href='{{ url_for("main.index") }}'>C🧭llege Navigator</a>
                {% for category, msg in get_flashed_messages(with_categories=true) %}
                    <h3 class="{{ category }}">{{ msg }}</h3>
                {% endfor %}
                <ul>
                    {% if current_user.is_authenticated %}
                        <li>Hi {{ current_user.name }}!</li>
                        <li>
                            <a href='{{ url_for("main.profile") }}'>Profile</a>
                        </li>
                        <li>
                            <a href='{{ url_for("auth.logout") }}'>Log out</a>
                        </li>
                    {% else %}
                        <li>
                            <a href='{{ url_for("auth.signup") }}'>Sign up</a>
                        </li>
                        <li>
                            <a href='{{ url_for("auth.login") }}'>Log in</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </body>
</html>

research_day9/navigator/templates/index.html
{% extends "base.html" %}
{% block content %}
    <section id="colleges">
        <table>
            <thead>
                <th>Name</th>
                <th>City</th>
                <th>State</th>
            </thead>
            <tbody>
                {% for item in data %}
                    <tr>
                        <td>{{ item.name }}</td>
                        {% if current_user.is_authenticated %}
                            <td>{{ item.city }}</td>
                        {% else %}
                            <td>{{ '*' * item.city|length }}</td>
                        {% endif %}
                        <td>{{ item.state }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td>Luther College</td>
                        <td>Decorah</td>
                        <td>Iowa</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock content %}

research_day9/navigator/templates/login.html
{% extends "base.html" %}
{% block content %}
    <section>
        <form method="post" action='{{ url_for("auth.login") }}'>
            {{ form.csrf_token }}
            {{ form.email.label }} {{ form.email(size=32) }}
            {{ form.password.label }} {{ form.password(size=32) }}
            <input type="submit" value="Log in">
        </form>
        {% if form.email.errors %}
            <ul class="errors">
                {% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}
            </ul>
        {% endif %}
    </section>
{% endblock content %}

research_day9/navigator/templates/signup.html
{% extends "base.html" %}
{% block content %}
    <section>
        <form method="post" action='{{ url_for("auth.signup") }}'>
            {{ form.csrf_token }}
            {{ form.email.label }} {{ form.email(size=32) }}
            {{ form.name.label }} {{ form.name(size=20) }}
            {{ form.password.label }} {{ form.password(size=32) }}
            <input type="submit" value="Create account">
        </form>
        {% if form.email.errors %}
            <ul class="errors">
                {% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}
            </ul>
        {% endif %}
    </section>
{% endblock content %}